<img src="https://upload.wikimedia.org/wikipedia/commons/b/b0/Logo_Universidad_Politécnica_Salesiana_del_Ecuador.png" width="90%">
<h2>Práctica 1:
    Redes neuronales</h2>
<h3>Integrantes: Michelle Parraga, Andrés Alba </h3>

a) modificar el cuaderno de tal manera que la red neuronal pueda aprender la compuerta NAND con 4 entradas.
La primera capa debe tener 64 neuronas y la segunda capa 1 neurona. Mostrar como salida el dataframe con las 
columnas: “predicción” y “real”


In [1]:
import numpy as np
import pandas as pd

In [20]:

#COMPUERTA NAND DE CUATRO ENTRADAS

import numpy as np
import pandas as pd

# Dataset: Entradas
X = np.array([[0, 0, 0, 0],
              [0, 0, 0, 1],
              [0, 0, 1, 0],
              [0, 0, 1, 1],
              [0, 1, 0, 0],
              [0, 1, 0, 1],
              [0, 1, 1, 0],
              [0, 1, 1, 1],
              [1, 1, 1, 1],#
              [1, 0, 0, 0],
              [1, 0, 0, 1],
              [1, 0, 1, 0],
              [1, 0, 1, 1],
              [1, 1, 0, 0],
              [1, 1, 0, 1],
              [1, 1, 1, 0],
              [1, 1, 1, 1],
              [0, 0, 0, 0],
              [0, 0, 0, 1],
              [0, 0, 1, 0],
              [0, 0, 1, 1],
              [0, 1, 0, 0],
              [0, 1, 0, 1],
              [0, 1, 1, 0],
              [0, 1, 1, 1],
              [1, 1, 1, 1]])#26

# Salidas reales -> Aprendizaje Supervisado
y = np.array([[1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [0],
              [1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [0],
              [1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [0]])

In [21]:
#Funciones

def sigmoid(z):
    """ función sigmoide """
    fz=1/(1+np.exp(-z))
    return fz

def derivada(fz):
    """ derivada de la función sigmoide """
    return fz*(1-fz)

def tanh(x):
    """ función tangente hiperbólica """
    return np.tanh(x)
 
def tanh_derivada(x):
    """ derivada de la función tangente hiperbólica """
    return 1.0 - x**2

In [38]:
# Construcción

#Como paso opcional, definimos una seed (semilla), para tener los mismo resultados, e inicializamos de forma aleatoria los pesos.
#La primera matriz de pesos tiene que ser de un tamaño fijo, en este caso (2,3) porque tenemos 2 valores de entrada 
#(es decir, 2 variables o características) y la siguiente capa tiene 3, entonces la salida tiene que tener la misma cantidad 
#de entradas que tiene la siguiente capa.

np.random.seed(1)

#syn0=np.array([[0.1,0.3,0.5],
#               [0.2,0.4,0.6]])
#syn1=np.array([[0.7],
#               [0.9],
#               [0.11]])

syn0 = 2*np.random.random((4,34)) - 1
syn1 = 2*np.random.random((34,1)) - 1

print('********** ENTRADAS')
print(X)
print('********** PESOS PARA CAPA DE ENTRADA')
print(syn0)
print('********** PESOS PARA CAPA DE SALIDA')
print(syn1)

********** ENTRADAS
[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 1 1 1]]
********** PESOS PARA CAPA DE ENTRADA
[[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822 -0.81532281
  -0.62747958 -0.30887855 -0.20646505  0.07763347 -0.16161097  0.370439
  -0.5910955   0.75623487 -0.94522481  0.34093502 -0.1653904   0.11737966
  -0.71922612 -0.60379702  0.60148914  0.93652315 -0.37315164  0.38464523
   0.7527783   0.78921333 -0.82991158 -0.92189043 -0.66033916  0.75628501
  -0.80330633 -0.15778475  0.91577906  0.06633057]
 [ 0.38375423 -0.36896874  0.37300186  0.66925134 -0.96342345  0.50028863
   0.97772218  0.49633131 -0.43911202  0.57855866 -0.79354799 -0.10421295
   0.81719101 -0.4127717  -0.42444932 -0.73994286 -0.96126608  0.35767107
  -0.57674377 

In [39]:
#Entrenamiento

for j in range(100000):#cantidad de epochs (un epoch es una pasada de forwarding y backpropagation)
    
    #1. Forward Propagation: 
    #producto punto de nuestros datos por nuestros pesos (Suma Ponderada) y lo pasamos por nuestra función de activación.
    #Y para la siguiente capa multiplicamos los valores de la capa anterior y nuestra capa de pesos de la segunda capa. 
    #A esto nos referimos a que están cada una de las neuronas de la capa anterior conectadas con las neuronas 
    #de la capa siguiente.

    l0 = X
    #print('********** X')
    #print(l0)
    l1 = sigmoid(np.dot(l0,syn0)) #np.dot(l0,syn0) es z  
    #print('********** Salidas de capa 1')
    #print(l1)
    l2 = sigmoid(np.dot(l1,syn1)) #Estas son las predicciones
    #print('********** Salidas de capa 2 (salida)')
    #print(l2)
    
    #2. Calculo del Error: entre predicciones actuales y reales para determinar la Función de Pérdida
    l2_error = y - l2
    #print('********** Errores en capa de salida')
    #print(l2_error)     
    
    #Algoritmo de Descenso de Gradiente: la pendiente (la tasa de cambio) se calcula multiplicando nuestra perdida actual 
    #con la derivada de nuestras predicciones actuales, de esta manera vamos a saber para que dirección ajustar los pesos.
    
    l2_delta = l2_error*derivada(l2) #es la pendiente (direcciones hacia donde mover pesos). 
    #n (tasa de aprendizaje) es 1. l2 son las predicciones actuales, es decir, las entradas X de la capa actual.
    #print('********** Gradiente en capa de salida')
    #print(l2_delta)
    
    #3. Backpropagation: propagar el error hacia atrás -> "la dirección hacia donde moveremos los pesos de la ultima capa"
    
    #multiplicar la pendiente "l2_delta" por la transpuesta de los pesos de la capa anterior "syn1.T", de este modo 
    #propagaremos el error hacia atrás, y de esta manera la capa anterior "l1" calculará la dirección "l1_delta" hacia 
    #donde debe mover los pesos "syn1" y "syn0".
    
    l1_error = l2_delta.dot(syn1.T)
    #print('********** Errores en capa 1')
    #print(l1_error)
    l1_delta = l1_error * derivada(l1)
    #print('********** Gradiente en capa 1')
    #print(l1_delta)
    
    #Finalmente, ajustamos el valor de nuestros pesos, multiplicando la transpuesta de la capa por sus respectivas 
    #optimizaciones, o direcciones hacia donde actualizar los pesos, y esto se suma a nuestros pesos actuales, 
    #actualizando las dos capas a la vez.
    
    syn1 += l1.T.dot(l2_delta)
    
    syn0 += l0.T.dot(l1_delta)

print('********** Pesos de capa 1')
print(syn0)
print('********** Pesos de capa 2 (salida)')
print(syn1)
print('********** Predicciones')
print(l2)

#Se presenta las entradas, los valores reales y predicciones
#Se forma un dataframe con X
df = pd.DataFrame(X, columns = ['X1','X2','X3','X4'])
df.head()
y_pred = (l2 >= 0.5).astype("int32")
y_pred = y_pred.flatten()# de 2D a 1D
y_real=y.flatten()
#Se forma un dataframe con los valores reales y predicciones
dataframeSalida=pd.DataFrame({'real':y_real, 'predicción': y_pred})
dataframeSalida.head()
#Se concatena los dataframes de X y los valores reales y de predicción, esto con respecto al eje 1 (columnas)
df=pd.concat([df, dataframeSalida], axis=1)
df.head(10)


********** Pesos de capa 1
[[-1.34887552  0.5746847  -3.61167018 -1.6899344  -0.06119911 -2.44672111
  -0.51223057 -0.93286782 -0.42990042 -0.01128025 -0.77951261 -0.16291414
  -2.11419338  1.7577744  -1.6346531   1.09962522  0.23737328 -0.39607826
  -0.55860769 -1.30486092  0.53767519  2.03386713 -2.00430387  0.18025462
   0.77797283  0.86889189 -0.81205425 -1.75890189 -0.84407978  1.69746799
  -0.58302875 -0.26373644  0.49100731  0.08428389]
 [-0.62144263 -1.23543199 -0.40146563  1.81133775 -0.7842169   0.97310294
   1.39988043 -0.02304375 -1.01914234  0.54276574 -1.91172487 -1.34389915
   1.47189004 -1.93170228 -1.16564964 -3.0083764  -2.2918335  -0.22893009
  -0.48933322 -1.05934083 -0.5949485  -2.50472898  0.83467076 -2.89248333
   0.18016153  0.32009009 -0.92665715  0.83628798  0.16602855 -1.7791622
  -0.8948627   0.12726111 -0.58882808 -0.13016311]
 [ 0.03319277 -0.2298956   0.52696305 -3.07537461 -0.37238991  1.583118
   0.11528125 -1.54571764  0.85872583 -0.94039608  0.0768118

X1  X2  X3  X4  real  predicción
0   0   0   0   0     1           1
1   0   0   0   1     1           1
2   0   0   1   0     1           1
3   0   0   1   1     1           1
4   0   1   0   0     1           1
5   0   1   0   1     1           1
6   0   1   1   0     1           1
7   0   1   1   1     1           1
8   1   1   1   1     0           0
9   1   0   0   0     1           1